# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Ref: https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers
trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE
    - CHANGELOG.md

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'
  displayName: Insalling node

- script: |
    npm install
    npm i -g eslint
  displayName: Installing eslint
- script: |
    eslint ./src/sxw.js
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: Eslint execution
